# Generated by Django 2.1.5 on 2019-04-03 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fb', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=100)),
                ('education_field', models.CharField(max_length=200)),
                ('work_as', models.CharField(max_length=50)),
                ('work_in', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
