# Generated by Django 2.1.5 on 2019-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='education_field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work_as',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work_in',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
