# Generated by Django 2.1.5 on 2019-04-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190404_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics'),
        ),
    ]
