# Generated by Django 2.1.5 on 2019-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190404_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.CharField(default='18', max_length=10),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
