# Generated by Django 2.1.5 on 2019-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190405_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ista',
            field=models.URLField(blank=True),
        ),
    ]
