# Generated by Django 2.1.5 on 2019-04-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userinfo_ista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ista',
            new_name='insta',
        ),
    ]
